### ISSUE TITLE
Support a list of file types.

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/galaxy_refseq_libraries#3]
Have a CL switch which adds a list of filetypes. 

* Supply a list of filetypes (fna, gff, gbk etc)
* Uses comma or space separated list.
* in XXX format.
* Defaults to "fna,faa,ffn,gbk,gff"

**Comment by Slugger70** [comment]
Could even have an inverse option. (get all files except...)

**Comment by madisonkeene** [comment]
This is now done- refseq version lives under the refseq branch in the repo (https://github.com/gvlproject/galaxy_refseq_libraries/tree/refseq_data_libraries)
